### ISSUE TITLE
Font Awesome version 4.1 introduces 'fa-header'

### ISSUE THREAD

**Issue by jeremylynch** [kevinoconnor7/pagedown-bootstrap#17]
In Font Awesome 4.1, `fa-header` has been introduced. The CSS hack in <a href="https://github.com/kevinoconnor7/pagedown-bootstrap/blob/1f8ccfac341a9c9a5f3ab869df5799f7339c96f3/css/jquery.pagedown-bootstrap.css">jquery.pagedown-bootstrap.css</a> is no longer needed for users with 4.1, how can we change the code to also accommodate those using 4.0? 

``` css
.fa-header:before{content:'H';font-family:arial,helvetica,sans-serif;font-weight:bold;}
```
